Develop v2 1
Open-Network-Models-and-Interfaces-ONMI/TAPI pull request #486
Opened 2020-06-03 14:05 UTC by amazzini

2020-06-08 23:59 UTC, karthik-sethuraman approved these changes

2020-06-09 14:20 UTC, karthik-sethuraman requested changes
Need to include YANG, TREE and OAS files

2020-06-15 13:16 UTC, arthurMll commented on YANG/tapi-photonic-media@2020-04-23.yang
> +    grouping media-channel-aconnectivity-service-end-point-spec {
Typo in the name: media-channel-**_a_**connectivitiy-service-end-point-spec

2020-06-15 13:16 UTC, arthurMll commented on YANG/tapi-photonic-media@2020-04-23.yang
> +        container media-channel-aconnectivity-service-end-point-spec {
Typo in the name: media-channel-**a**connectivitiy-service-end-point-spec

2020-06-15 13:47 UTC, arthurMll commented
I have reviewed the .yang .tree files and it seems they do not match. I think the tree files are generated wrong or based in an intermediate version of the YANG files.

2020-06-17 23:45 UTC, amazzini commented
Also renamed
- OtsiAConnectivityServiceEndPointSpec as OtsiaConnectivityServiceEndPointSpec
- MediaChannelAConnectivityServiceEndPointSpec as McaConnectivityServiceEndPointSpec

2020-06-18 11:31 UTC, nigel-r-davis commented
I have just reviewed the photonic media model and yang and have found another name issue following the OtsiAConnect... pattern. There is an OtsiGServerAdaptationPac. This comes out as otsi-gserver.... It ought to be otsig-server..., hence the uml should be OtsigServerAdaptationPac. There are also two forms, Otsia... and OtsiAssembly... in the uml. The OtsiAssemblyConnectionEndPointSpec... ought to be OtsiaConnectionEndPointSpec. 

Unfortunately we also have an longhand media-channel-assembly-spec - this may be arguable because we are using longhand media-channel everywhere else not mc, so the distinction between OTSI and MC is set in general. 

I suggest we stay with media-channel-assembly, but ought to fix the Otsig issue (as it is exactly the same pattern as the Otsia issue we have already fixed. We could consider the OtsiAssembly issue from a consistency perspective, but I am ok to leave it as is.

2020-06-18 11:35 UTC, nigel-r-davis commented
Have just realized that the two items I commented on are both deprecated.

I have no issue with the PhotonicMedia model as it is.

2020-06-18 11:37 UTC, nigel-r-davis approved these changes
To the depth I have managed to review, I am OK to proceed.

2020-06-18 15:01 UTC, arthurMll approved these changes
Everything seems correct. Approved from my side.

2020-06-18 21:58 UTC, karthik-sethuraman approved these changes

2020-06-19 14:05 UTC, merged